stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
      - src/data/data_ingestion.py
    params:
      - data_ingestion.test_size
    outs:
      - data/raw

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
      - data/raw
      - src/data/data_preprocessing.py
    outs:
      - data/processed

  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
      - data/processed
      - src/features/feature_engineering.py
    params:
      - feature_engineering.max_features
    outs:
      - data/features/train_tfidf.csv
      - data/features/test_tfidf.csv

  model_building:
    cmd: python src/model/model_building.py
    deps:
      - src/model/model_building.py
      - data/features/train_tfidf.csv
      - data/features/test_tfidf.csv
    params:
      - model_building.n_estimators
      - model_building.learning_rate
    outs:
      - model/model.pkl

  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
      - model/model.pkl
      - src/model/model_evaluation.py
      - data/features/test_tfidf.csv
    metrics:
      - metrics/metrics.json



